#!/bin/bash
sudo
clear
echo "Notice: All files besides 'update.sh' in this folder are DELETED. FOREVER. "
echo "Ctrl + C to cancel."
sudo rm log,txt
sleep 5
echo 'no cancel YES' >> log,txt
sudo rm readme.md
#sudo rm upgrade.sh <-- ignore.
sudo rm -rf zip
clear
echo "installing/updating - apt"
sudo apt -qq update
echo 'apt update 1 YES' >> log,txt
clear
echo "installing Zip and UnZip"
sudo apt install zip unzip wget -y 
sudo apt -qq update
echo 'apt update 2 YES' >> log,txt
clear
echo "installing/updating update - OK"
sudo apt -qq upgrade -y
echo 'apt upgrade YES' >> log,txt
clear
echo "installing/updating upgrade - OK"
# ONLY CHANGE THIS LINK!
wget https://github.com/Nolanrulesroblox/SU-v2/blob/zip-mode/zip.zip?raw=true
# ONLY.
sudo mv zip.zip?raw=true zip.zip
echo "installing/updating download - OK"
echo 'wget download zip 1 - OK' >> log,txt
sleep 1
echo "updating and making folders"
sudo mkdir zip
sudo chmod 777 zip
echo "chmod 777 - OK"
echo "mkdir zip - OK"
echo 'chmod 777 1 YES' >> log,txt
echo 'mkdir zip 1 YES' >> log,txt
sleep 1
clear
cp zip.zip zip
sudo rm zip.zip
cd zip
clear
unzip zip.zip
sudo rm zip.zip
clear
echo "updated"
sleep 3
clear
sudo sh upgrade.sh
cd ..
sudo chmod 777 zip
sudo rm -rf zip
clear
echo "temp files cleared."
echo "Upgraded/Updated - OK"
echo 'updated/installed FULL - YES' >> log,txt
exit
#DO NOT EDIT THIS FILE.