#!/bin/bash
sudo
clear
echo "Notice: All files besides 'update.sh' in this folder are DELETED. FOREVER. "
echo "Ctrl + C to cancel."
sleep 3
sudo rm readme.md
sudo rm upgrade.sh
clear
echo "installing/updating git and git repo"
sudo apt -qq update
clear
echo "installing/updating git and git repo"
sudo apt -qq install git -y
clear
echo "installing/updating git and git repo"
sudo apt -qq update
clear
echo "installing/updating git and git repo"
sudo apt -qq upgrade -y
clear
echo "installing/updating git and git repo"
git clone https://github.com/Nolanrulesroblox/SU-v2.git
cd SU-v2
clear
# put your git link above
clear
echo "updated"
sleep 3
clear
sudo sh upgrade.sh
cd ..
sudo chmod 777 SU-v2
sudo rm -rf SU-v2
clear
echo "temp files cleared."
echo "Upgraded/Updated 100%"
exit
#DO NOT EDIT THIS FILE.